version: '2'
services:
  consul:
    image: progrium/consul
    restart: always
    command: "/bin/start -server -bootstrap"
    expose:
     - "8400"
     - "8500"
     - "53/udp"
  adminui:
    image: albi/adminui
    depends_on:
      - consul
    expose:
     - "8080"
    environment:
    - "SPRING_CLOUD_CONSUL_HOST=consul"
