spring:
  application:
    name: video
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-connection-idle-timeout-seconds: 3
    registry-fetch-interval-seconds: 10
ribbon:
  http:
    client:
      enabled: true
